# Use root/example as user/password credentials
# este compose incluye la base de datos en otro docker y levanta aplicacion y DB juntos
version: '3.1'

services:
  db:
    image: pandorafms/pandorafms-percona-base:80
    restart: always
    command: ["mysqld", "--innodb-buffer-pool-size=1G"] 
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: pandora
      MYSQL_DATABASE: pandora
      MYSQL_USER: pandora
      MYSQL_PASSWORD: pandora
    networks:
     - pandora
networks:
  pandora: